mong/imongr

.lintr, R/aggregate.R, R/ops.R, tests/testthat/test-ops.R, tests/testthat/test-upload.R
Added nolint behind lines where PascalCase are used (variable names).
Should consider renaming OrgNr, KvalIndID etc.
=> Remove lintr warnings

DESCRIPTION
=> No longer depends on github version of shiny

.github/workflows/R-CMD-check.yml, DESCRIPTION
The source build of `RMariaDB` failed on Windows. Build dependencies with `type="binary"` to fix this. 
```r
remotes::install_deps(dependencies = TRUE, type="binary")
```
=> Install binaries on github actions 

docker-compose.yml
Was probably using `latest`, which was outdated
=> Force dev service to use master version of mongr-dev

docker-compose.yml
They are defined in mong/mongr-dev
=> Remove unnecessary enviroment statements in dev service

docker-compose.yml
This reverts commit 90b2bd6284caff20fc0c70dbde99b32fdbd90d8e.
We have started with releases of mongr-dev and therefore latest tag will be the lastest release. It will also make it possible to install local versions of mongr-dev.
=> Revert "Force dev service to use master version of mongr-dev (#232)"

.lintr
+ Use linters_with_defaults instead of with_defaults (deprecated)
=> Allow 120 characters per line

R/mod_upload.R, tests/testthat/test-mod.R
The data will only contain numbers, ind_id and context. Thus, no non-ascii characters.
=> Remove choose encoding option

R/mod_indicator.R
`set_level_yellow` ble ikke vist hvis `level_yellow` var `NULL` i databasen. Dette ga en del kluss siden `level_yellow` fra tidligere indikator ble bruk i app for å bestemme om grønt nivå var riktig satt (`level_consistent`).
Closes #271
=> Mulighet til å velge gult målnivå hvis grønn er NULL

DESCRIPTION, R/mod_download.R
Fikser #281. Nedlastede filer i csv-format har ikke lenger " " rundt strenger.
=> Fjern anførselstegn i csv-filer som lastes ned

R/db_get.R, R/ops.R, man/db_get.Rd, man/ops.Rd, tests/testthat/test-db.R, tests/testthat/test-ops.R
Gikk tidligere gjennom alle indikatorene og dataene i hele databasen. Dette tok veldig lang tid.
Closes #216
=> update_aggdata_delivery kun på aktuelle register

R/ops.R
```
Warning (test-db.R:128:3): agg_data can be populated from existing (test) data
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
ℹ Please use `"short_name"` instead of `.data$short_name`
Backtrace:
▆
1. ├─testthat::expect_message(insert_agg_data(pool, data_sample)) at test-db.R:128:2
2. │ └─testthat:::quasi_capture(enquo(object), label, capture_messages)
3. │   ├─testthat (local) .capture(...)
4. │   │ └─base::withCallingHandlers(...)
5. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
6. ├─imongr::insert_agg_data(pool, data_sample)
7. │ └─... %>% dplyr::rename(unit_name = .data$short_name) at imongr/R/ops.R:190:2
8. ├─dplyr::rename(., unit_name = .data$short_name)
9. └─dplyr:::rename.data.frame(., unit_name = .data$short_name)
10. …
```
=> Fjernet dplyr-advarsel

.github/workflows/R-CMD-check.yml
`make_pool` trenger en database for å gjøre første tilkobling, så git workflow-filen må lage en dummy-database.
=> Oppdater git workflow

docker-compose.yml
Flyttet en del definisjoner som ble brukt av flere ut i egne definisjoner. Det var stort sett samme definisjoner på alle database-instansene, og stort sett de samme miljøvariabel-definisjonene i de to dev-instansene og i app.
Definerer også miljøvariablene her i stedet for i docker-imaget til `mongr-dev-*`. Dropper derfor å inkludere `.Renviron`-fil i https://github.com/mong/mongr-dev/pull/52
Dropper pålogging til rstudio (`DISABLE_AUTH: "true"`).
=> Forenkling av docker-compose med yaml-merge

Dockerfile
imongr did not work with bslib v6 when setting bootstrap version to 4. See issue #380
Will probably be a problem when imongr-base-r are updated
=> Install older version of bslib

Dockerfile, R/mod_publish.R, docker-compose.yml, inst/terms.Rmd
Dropper pdf av terms. Kjører på MariaDB 10 i stedet for 11. Fjernet innhold i rmd-fil som ga feilmelding om Cairo
=> Prep. for alpine

docker-compose.yml
Nye versjoner av utviklingsmiljø etc. ble ikke hentet ned automatisk, så man kunne ende opp med å kjøre eldre versjoner
=> Angi versjon av docker image i docker-compose

R/mod_review.R
[Endringer i ggplot versjon 3.5.0](https://ggplot2.tidyverse.org/news/index.html) gjør at symboler i tegnforklaringen ikke vises hvis det ikke finnes data: 
> By default, [guide_legend()](https://ggplot2.tidyverse.org/reference/guide_legend.html) now only draws a key glyph for a layer when the value is in the layer’s data. To revert to the old behaviour, you can still set show.legend = c({aesthetic} = TRUE)
=> Fiks tegnforklaring i graf

R/mod_upload.R
Endret fra 'Merk alle indikatorer som forel\u00f8pig etter:' til 'Dataene er komplette til:'. Dette tilsvarer det som står på nettsidene.
Closes #422
=> Endret tekst over latest_affirm-dato

R/db_get.R, inst/imongr.yml
Ingen indikatorer som lenger har denne typen, og vi vil heller ikke ha den
=> Fjernet type dg_beregnet_andel

Dockerfile
Dukket opp i alle pull requests
=> Fjernet advarsel om 'legacy key/value format' i docker-fil

R/mod_indicator.R, inst/imongr.yml
Nedtrekksmenyen til indikatorformat viser nå "prosent" og "desimaltall" istedenfor "%" og "f":
=> Navn på valg av format i indikatorfane

R/mod_indicator.R, R/mod_publish.R, R/mod_review.R, R/server_output.R, inst/imongr.yml
Farge på knapper som dukker på under 'Last opp data', 'Publiser indikatorer' og 'indikatorer', totalt fire knapper.
Bruker samme stil som i ekspertgruppe-fane.
Closes #485
=> Grønn farge på publiser-knapper

docker-compose.yml
Gjør det mulig å kjøre opp api-docker-image lokalt, som bruker db-instansen for å hente data.
=> API i docker-compose-fila

R/app_server.R
Imongr starter opp admin-fanen med verify som kontekst, men henter data fra prod. Listene over fagområder og brukere viser derfor prod-data frem til at man endrer kontekst eller trykker på knappen for å oppdatere.
=> Fikset bug i brukerliste og fagområdeliste

.lintr, _pkgdown.yml
cyclo-greiene kjøres ikke lenger som default, og ville trengt en pakke for å kjøre
=> Fiks lintr-jobb

inst/2_create_tabs.sql
Rad med primær-id ble automatisk opprettet i databasen, så lager dem eksplisitt her isteden.
=> Lagt til id i databaseskjema for kvalitetsforbedringsprosjekter

R/checks.R, R/mod_project.R
Hvis man oppdaterer årstall og deretter oppdaterer tekst vil knappen for å oppdatere verdier vises. Dette skjer fordi prosjektverdiene er en reaktiv variabel som ikke trigges av at man oppdaterer verdier. 
I tillegg skal ikke `end_year` regnes som en manglende verdi. Den vil uansett være `NA` og ikke `NULL`.
=> Fikset bug i projektfanen

R/db_get.R, R/mod_project.R, R/mod_selected_indicators.R
Foreslår at vi beholder indikator-id i indikatorfanen siden de bruker denne når de laster opp data. 
Fanene for kvalitetsforbedring og utvalgte indikatorer blir slik:
=> Fullt indikatornavn i faner for kvalitetsforbedring og utvalgte indikatorer
