mong/imongr

R/app_server.R, inst/imongr.yml
=> upload reciept

R/aggregate.R, inst/2_create_tabs.sql, inst/imongr.yml
Renaming two fields in agg_data
=> Count to denominator

R/app_server.R
=> Aggregate before putting raw data in db

DESCRIPTION, NEWS.md, R/aggregate.R
Add (missing) endpoints for 'green' when aggregating levels close #72
=> Post prod fixes

R/app_server.R
This reverts commit 144ac9416511ca529b95357815481fc74da0cc3e.
PR #66 was a draft and had some bad side effects.
=> Revert "Aggregate before putting raw data in db"

.github/workflows/R-CMD-check.yml, .github/workflows/coverage.yml, .github/workflows/lintr.yml, README.md
=> Fix github action tests (macOS)

R/app_ui.R
Was only used one place. Do not have to define it. The default color was OK.
=> rm some css color def

DESCRIPTION, NEWS.md, R/server_output.R
Not only the one the user can deliver data to.
=> Show all registry in fagomr tab

.github/workflows/lintr.yml, R/aggregate.R
`lint_package` returned a lot of false positive. Will close #108
=> gh actions: Install package before lintr

.github/workflows/docker.yml
Repo just moved. Using newest version with new tag system.
Have been using it on mong/tmongr
=> Use docker/metadata-action instead of crazy-max

.github/workflows/R-CMD-check.yml
Once a day is maybe too much (save some energy)?
=> Github actions: only run once a week

inst/a_alter_tabs.sql
This error (and its fix) relates to the dev environment for imongr only
=> Wrong alter sql

Dockerfile
Change needed before merging #152
=> new base R v 4.1.2

.github/workflows/R-CMD-check.yml
Fixing previous introduced new error
=> ga: fix only whats broken

docker-compose.yml
Thus, make it possible for [mongts](https://github.com/mong/mongts) to use it
=> Expose db to the ouside

docker-compose.yml
Koden man da ser i utviklermiljøet er det samme man ser utenfor, og man endre i koden lokalt på egen maskin utenfor docker.
=> Monter nåværende kildekode (.) i docker-compose

R/aggregate.R, R/db_get.R, R/ops.R, R/report.R, R/upload.R
Appen spyttet ut en del advarsler under testing:
```
Use of .data in tidyselect expressions is now deprecated
```
=> Erstattet .data$n med "n" i dplyr::select

Dockerfile, README.md, docker-compose.yml
=> README: Hvordan kjøre Docker-fil lokalt

R/mod_indicator.R
Going from 47 to 27 in R/mod_indicator.R
=> Reduce cyclomatic complexity

R/mod_indicator.R
As done for 'Oppdater verdier'.
Closes #259
=> Only show 'Oppdater tekster' button when new text

R/mod_publish.R
The values type, min_denominator, level_green, level_yellow and level_direction are now published.
Closes #256
=> Update ind values when publishing

R/mod_indicator.R
=> Remove error/warning when opening indicator tab

R/mod_indicator.R
=> Do not aggregate data if updating ind table

R/mod_indicator.R
Ble kluss i indikatorfane når tekst-feltene var tomme (NA/NULL i db). Closes #273
=> Erstatt NA med tom tekst

DESCRIPTION, Dockerfile, NEWS.md, R/app_server.R, R/mod_publish.R, man/mod_publish.Rd
Fikset #268. Det skal nå fungere å endre på en indikator, bytte fane og publisere uten å måtte laste inn appen på nytt.
=> Sjekk om data kan publiseres når man bytter til publiseringsfanen

inst/imongr.yml
Fjernet telefonnummer og lagt inn kontaktinformasjon til Arnfinn og Stein-Kato. Fjernet Are som kontaktperson
=> Endret hjelpetekst

R/misc.R, R/mod_upload.R, R/ops.R, R/server_output.R
Bruker får nå beskjed dersom samme datafil har vært lastet opp tidligere.
=> Issue 297 sk

R/upload.R, inst/imongr.yml
Har lagt til en sjekk ved opplasting av data for om beregnede indikatorer er duplisert. 
Dette burde løse #229 og #302 etter at duplikater er fjernet fra databasen.
=> Duplikater i aggdata

DESCRIPTION, NEWS.md
=> Oppdatert NEWS + Stein-Kato som forfatter

R/aggregate.R
Bruk kortnavn for å slå sammen dekningsgrad og indikator istedenfor orgnummer
=> Legg på dekningsgrad basert på kortnavn

R/mod_publish.R
=> Åpne lenke til verify-side i ny fane

R/db_get.R, R/mod_indicator.R, man/db_get.Rd
særnorsk bokstav og udokumentert variabel
=> Fjerne ett par advarsler

.github/workflows/docker.yml
Må inn før vi kan aktivere ny EC2-instans, som kjører på ARM.
=> Bygg og dytt opp docker-image for arm64 parallelt med amd64

R/aggregate.R, R/app_server.R, R/app_ui.R, R/mod_publish.R, R/ops.R, inst/imongr.yml, tests/testthat/test-mod.R, tests/testthat/test-ops.R
Nytt loggvindu i publiseringsmodulen som viser fremdrift. 
Programmet kræsjer ikke lenger hvis noe går galt, men kjører videre. Feilmeldinger blir røde i loggen.
=> Fremdriftslogg og feilhåndtering under publisering og aggregering

R/mod_indicator.R
Ctrl+v-feil fra tidligere pull request
=> Bugfiks på "oppdater verdier"-knapp i indikatorfanen

R/upload.R, tests/testthat/test-upload.R
La imongr sjekke at data er korrekt i henhold til indikatortabell i verify før data og indikatortabell overføres til prod.
=> Sjekk data mot oppdatert indikatortabell

R/mod_profile.R, inst/imongr.yml
=> Bugfiks i profiltab

R/mod_review.R
Pluss fiksing av bug som gjorde at vurderingstekst ikke opdpaterte seg når man byttet år eller register.
=> Endret tidligste valgbare år i ekspertgruppefanen

Dockerfile, R/app_ui.R
Gammel versjon:
Ny versjon:
Hvis jeg fjerner alt av styling:
=> Bruk bootstrap 5 i stedet for 4

R/mod_review.R
Denne går eventuelt inn i #402
=> Litt luft mellom ansvarlig-grupper

R/db_get.R, R/mod_review.R, inst/2_create_tabs.sql
Det er lagt til en ny kolonne `role` i `user_registry`-tabellen. Den kan være `NULL` og skal ikke påvirke andre ting.
=> Vis navn på hoved- og leseansvarlige i ekspertgruppefanen

R/app_server.R
=> Dropp å printe locale til logg

R/mod_review.R, tests/testthat/test-mod.R
- Ingen nivåer før 2019
- Vis dekningsgrad 0 som NA i graf og tabell
- Knapp for å hente fjorårets registreringer
- Flyttet kode til egne funksjoner
=> Nye features i ekspertruppefanen

R/mod_review.R
=> Forbedring av vurderingsfanen

R/server_output.R
Enklere å gå gjennom lista under referansegruppemøtet.
Closes #357
Fra
til
=> Vis navn på bruker i Brukere-siden

.github/workflows/R-CMD-check.yml, .github/workflows/coverage.yml, .github/workflows/ghpages.yml
Var veldig mye manuelt oppsett for å installere avhengigheter. Fikses av setup-r-dependencies-action
Vil sannsynligvis gå fortere nå, pga bedre cache av pakker etc.
=> Modernisert github actions

R/mod_review.R
=> Fjerning av  feilmelding i ekspersgruppefane

R/mod_review.R
=> Farge på lagre-knapp i ekspertgruppeskjema

inst/imongr.yml
=> Endre advarsel i opplasting og publisering

.github/workflows/R-CMD-check.yml, .github/workflows/docker.yml, .github/workflows/ghpages.yml
Ble for mye renovate. Hadolint må være spesifikk
=> Kun kjøre hovedversjon av gh-actions

.github/workflows/R-CMD-check.yml, .github/workflows/docker.yml, .github/workflows/ghpages.yml, .github/workflows/lintr.yml
Kjørte i dag på enten Ubuntu 22.04 eller Ubuntu latest
=> Kjør gh-actions på ubuntu 24.04

R/mod_indicator.R, inst/imongr.yml
Sidene er nå behandlingskvalitet/sykehusprofil
=> Fjern navnet Sykehusviser

.github/workflows/R-CMD-check.yml, .github/workflows/coverage.yml, .github/workflows/docker.yml, .github/workflows/ghpages.yml, .github/workflows/lintr.yml
Kun kjør github actions på siste commit
=> Drep samtidige jobber

R/mod_indicator.R
=> Bryter istedenfor sjekkboks på "Vis indikator"

R/db_get.R, R/mod_project.R, tests/testthat/test-db.R
Plot i kvalitetsforbedringsfanen som viser dataene som er lagt inn:
=> Kvalitetsforbedringsfigur
